### ISSUE TITLE
Export multiple files at a time

### ISSUE THREAD

**Issue by torphix** [KellanHiggins/UnityFBXExporter#47]
Hi there, Thanks for the great lib..

is it possible to export say 10 prefabs as fbx files at a time?

Thanks

**Comment by KellanHiggins** [comment]
So if you select 10 prefabs you can hit export 10 prefabs? If so, no there isn't. The problem is how do you figure out the grouping. Do you want each prefab it's own FBX? What if you have prefabs within other prefabs? What is the top level thing.

How many FBXs are you exporting? You can pretty easily set up a keyboard shortcut for the exporter if you are tired of clicking.

**Comment by torphix** [comment]
Thanks for the response,
Your analysis is correct.
The issue arises when grouping fbxs as one as either the pivot point is
maintained relative to the group of fbxs or you have to export one by one.

Also the collision meshs are not exported when importing the fbx file into
ue4, or they are but it is very simple collision mesh generally just a
square around the object, any thoughts?

Thanks

**Comment by KellanHiggins** [comment]
No the collision meshes aren't supported unfortunately. FBX doesn't support any type of collision mesh (those are specific to each game engine). I suppose that you could write out an FBX that had all the box colliders, mesh colliders etc written as objects and then use those as mesh colliders in each program, but then a box collider would always become a more expensive mesh collider.

Unity does have it's own FBX exporter (written after I made this) and you may want to check that out. It is here https://docs.unity3d.com/Packages/com.unity.formats.fbx@2.0/manual/index.html

I've never used it though!

**Comment by torphix** [comment]
Thanks!
