### ISSUE TITLE
Exporting FBX from a WebGL build

### ISSUE THREAD

**Issue by usama-riaz-kc** [KellanHiggins/UnityFBXExporter#56]
Hello. I've been using this library to export FBX file of the current model in the scene and download it. However, it always comes up without any materials, and the ones being created including materials are being created via an editor script. Any solution to add materials in the main fbx file, which can be downloaded?

**Comment by KellanHiggins** [comment]
Hi @usama-riaz-kc, sorry for the late reply.

Unfortunately FBX only supports limited materials in albedo and the normal/bump map. There is now way to export it as a group out into the FBX format since the two material formats are very different. If you find a good solution, please post it here!

Cheers,
